apiVersion: v1
kind: Secret
metadata:
  name: hjimin-containerrobot-pull-secret
  namespace: dolphin
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhR3BwYldsdUsyTnZiblJoYVc1bGNuSnZZbTkwT2pGSlZGWkdOMGd6U3pWV1NFdE5VazVQTmtZd1FsTkZWMDlDVlRNek1sa3pRa0ZEVVVwTk16YzVSVlkzVmtoUk9WTldSMVJFVnpnd05URllORTVSTTB3PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson