apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: kube-system
data:
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks/logs
      mountDir: /mnt/disks/logs
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
        - "/scripts/dd_zero.sh"
      volumeMode: Filesystem
      fsType: ext4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: kube-system
  labels:
    app: local-volume-provisioner
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-provisioner-runner
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        effect: NoSchedule
        operator: Exists
      containers:
      - name: provisioner
        image: quay.io/external_storage/local-volume-provisioner:latest
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /mnt/disks/logs
          name: local-disks
        - mountPath: /etc/provisioner/config
          name: provisioner-config
        - mountPath: /mnt/helm/charts
          name: provisioner-scripts
      volumes:
      - name: local-disks
        hostPath:
          path: /mnt/disks/logs
      - name: provisioner-config
        configMap:
          name: local-provisioner-config
      - name: provisioner-scripts
        configMap:
          name: local-provisioner-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-provisioner-runner
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-provisioner-runner
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-provisioner-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-provisioner-runner
subjects:
- kind: ServiceAccount
  name: local-provisioner-runner
  namespace: kube-system
---