apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: dolphin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage