apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolphin-operator
  namespace: dolphin
spec:
  replicas: 2
  selector:
    matchLabels:
      io.dolphin/app: operator
      name: dolphin-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dolphin-operator
        app.kubernetes.io/part-of: dolphin
        io.dolphin/app: operator
        name: dolphin-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                io.dolphin/app: operator
            topologyKey: kubernetes.io/hostname
      automountServiceAccountToken: true
      containers:
      - args:
        command:
        - /usr/bin/dolphin-operator
        # - --enable-k8s=true
        # - --k8s-kubeconfig-path=/root/.kube/config
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: DOLPHIN_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DOLPHIN_DEBUG
          valueFrom:
            configMapKeyRef:
              key: debug
              name: dolphin-config
              optional: true
        - name: KUBERNETES_SERVICE_HOST
          value: 10.0.2.102
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        name: dolphin-operator
        image: docker.io/jimin1/dolphin-operator-generic:0427
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - name: dolphin-config-path
          mountPath: /tmp/dolphin/config-map
          readOnly: true
        # - name: kubeconfig
        #   mountPath: /root/.kube/config
        #   readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: dolphin-operator
      serviceAccountName: dolphin-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: dolphin-config
        name: dolphin-config-path
      # - name: kubeconfig
      #   hostPath:
      #     path: /root/.kube/config  # Adjust /home/$USER_NAME/.kube/config path as needed
      #     type: File
