apiVersion: v1
kind: Namespace
metadata:
  name: dolphin-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: dolphin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dolphin-operator
  namespace: dolphin