name: Image CI Builder

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - development

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build-and-push-prs:
    timeout-minutes: 45
    name: Build and Push Images
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout V1 code (trusted)
        uses: actions/checkout@v4
        with:
          ref: V1

      - name: Set up Docker Buildx (for caching)
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker layer caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.ref_name }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Getting image tag
        id: tag
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "" ]; then
            echo "tag=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y make

      - name: Build Docker image using Makefile
        env:
          DOCKER_BUILDKIT: 1
        run: |
          make docker-operator-image-generic

      - name: Tag the Docker image
        run: |
          docker tag dolphin-operator-generic:latest jimin1/dolphin-operator-generic:${{ steps.tag.outputs.tag }}

      - name: Push the Docker image
        run: |
          docker push jimin1/dolphin-operator-generic:${{ steps.tag.outputs.tag }}

      - name: Save Docker Image as Tar
        run: |
          docker save -o dolphin-operator-generic.tar dolphin-operator-generic:latest

      - name: Create Release and Upload Docker Image Tar
        uses: softprops/action-gh-release@V1
        with:
          files: dolphin-operator-generic.tar  # Path to the file to upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  image-digests:
    if: ${{ always() }}
    name: Display Digests
    runs-on: ubuntu-22.04
    needs: build-and-push-prs

    steps:
      - name: Download Dolphin Operator Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: dolphin-operator-image
          path: image-digest/

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
