name: Deploy Image into Kind Cluster

on:
  workflow_run:
    workflows: ["Image CI Builder"]
    types:
      - completed

jobs:
  deploy-to-kind:
    name: Deploy to Kind Cluster
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create host directories
        run: |
          sudo mkdir -p /tmp/kind-node1-logs /tmp/kind-node2-logs
          sudo chmod 777 /tmp/kind-node1-logs /tmp/kind-node2-logs
          sudo mount --bind /tmp/kind-node1-logs /tmp/kind-node1-logs
          sudo mount --bind /tmp/kind-node2-logs /tmp/kind-node2-logs

      - name: Set up Kind
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
          config: .github/kind-config.yaml

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      # - name: Download Dolphin Operator Image from GitHub Release
      #   run: |
      #     curl -LJO https://github.com/ccfish2/controllerPoweredByDI/releases/download/civ1/dolphin-operator-generic.tar

      # - name: Load Docker Image into KinD
      #   run: |
      #     kind load image-archive ./dolphin-operator-generic.tar
      - name: Checkout infra repo (with CRD yamls)
        uses: actions/checkout@v4
        with:
          repository: ccfish2/infra
          token: ${{ secrets.GITHUB_TOKEN }}
          path: infra

      - name: Deploy local volume provisioner and wait for PV
        run: |
          kubectl apply -f install/localstorage/localvolumeprovisioner.yaml
          if kubectl -n kube-system rollout status ds/local-volume-provisioner --timeout=2m; then
            echo "DaemonSet local-volume-provisioner rolled out successfully"
          else
            echo "DaemonSet local-volume-provisioner rollout failed or timed out"
            exit 1
          fi

          # Wait for at least 2 Available PVs on different nodes
          timeout=120  # 2 minutes
          interval=5   # check every 5 seconds
          elapsed=0

          while [ $elapsed -lt $timeout ]; do
              # Get count of Available PVs per node
              current_count=$(kubectl get pv --no-headers | awk '/Available/ {print $0}' | wc -l)

              if [ "$current_count" -ge 2 ]; then
                  echo "Found 2 Available PVs"
                  exit 0
              else
                  sleep $interval
                  elapsed=$((elapsed + interval))
              fi
          done

          echo "Timeout reached. Did not find at least 2 Available PVs."
          exit 1

      - name: Deploy the  CRD YAMLs
        run: |
          kubectl apply -f infra/pkg/k8s/apis/dolphin.io/client/crd/bases
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
          kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
      
      - name: Crete imagepull secret 
        run: |
          kubectl create ns dolphin
          kubectl create secret docker-registry quay-secret \
            --docker-server=quay.io \
            --docker-username=${{ secrets.QUAY_USER }} \
            --docker-password=${{ secrets.QUAY_PASSWD }} \
            --docker-email=dummy@example.com \
            --namespace=dolphin \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy using install/manifests (override image)
        run: |
          echo "Deploying image: quay.io/${{ secrets.QUAY_ORGANIZATION_DEV }}:${{ needs.build-and-push-prs.outputs.image_tag }}"
          kubectl create namespace dolphin || true
          for file in install/manifests/kindenv/*.yaml; do
            sed "s|image: .*|image: quay.io/${{ secrets.QUAY_ORGANIZATION_DEV }}:${{ github.event.workflow_run.head_sha }}|g" "$file" | kubectl apply -n dolphin -f -
          done
  
      - name: Wait for pvc to be ready 
        run: |
          NAMESPACE="dolphin"

          # Function to check PVC status
          check_pvc_status() {
              # Get the PVC status for the given namespace
              PVC_STATUS=$(kubectl get pvc -n "$NAMESPACE" --no-headers -o custom-columns=":status.phase")

              # Check if all PVCs are in 'Bound' status
              for status in $PVC_STATUS; do
                  if [[ "$status" != "Bound" ]]; then
                      return 1
                  fi
              done

              # If all PVCs are in 'Bound' status
              return 0
          }

          # Check PVC status
          if check_pvc_status; then
              echo "All PVCs are in 'Bound' status."
              exit 0
          else
              echo "Some PVCs are not in 'Bound' status. Waiting for 2 minutes..."
              sleep 120
              # Re-check PVC status after 2 minutes
              if check_pvc_status; then
                  echo "All PVCs are now in 'Bound' status."
                  exit 0
              else
                  echo "PVCs are still not in 'Bound' status after waiting."
                  exit 1
              fi
          fi

      - name: Wait for statefulset to be Ready
        run: |
          if kubectl rollout status statefulset/operator-dolphin -n dolphin --timeout=120s; then
            echo "statefulset operator-dolphin rolled out successfully"
          else
            echo "statefulset operator-dolphin rollout failed or timed out"
            exit 1
          fi
      
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
  
      - name: Run Operator Tests
        run: |
          bash .github/actions/tests/kindenv/operator-tests.sh
      
      - name: Run Network Tests
        run: |
          bash .github/actions/tests/kindenv/network-tests.sh

      - name: Delete KinD cluster
        if: always()
        run: kind delete cluster

